spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=150503

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2hpdG1lYXRoZXNlY3JldGtleWZvcmp3dHNnZW5lcmF0aW9uMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.expiration-ms=86400000

spring.data.redis.host=localhost
api.base-uri=/api/v1

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.consumer.group-id=shop-payment-results
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer

spring.task.scheduling.pool.size=1
