spring.application.name=ecommerce

spring.datasource.url=jdbc:postgresql://localhost:5433/ecommerce_db
spring.datasource.username=postgres
spring.datasource.password=150503

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=Y2hpdG1lYXRoZXNlY3JldGtleWZvcmp3dHNnZW5lcmF0aW9uMTIzNDU2Nzg5MDEyMzQ1Njc4OTA=
jwt.expiration-ms=86400000

