ALTER TABLE orders DROP CONSTRAINT chk_order_status;

ALTER TABLE orders ADD CONSTRAINT chk_order_status
    CHECK (status IN ('CREATED','PAYMENT_PENDING','PAID','FULFILLED','CANCELLED','PAYMENT_FAILED','NOT_COMPLETED'));
