-- V1: Initial schema + data

-- ============================================================
-- USERS
-- ============================================================
CREATE TABLE users (
    id bigint NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    role character varying(255) NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['CUSTOMER'::character varying, 'ADMIN'::character varying])::text[])))
);

ALTER TABLE users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME users_id_seq START WITH 1 INCREMENT BY 1);

ALTER TABLE users ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);

-- ============================================================
-- CATEGORIES
-- ============================================================
CREATE TABLE categories (
    id bigint NOT NULL,
    description character varying(255),
    name character varying(255) NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    CONSTRAINT categories_pkey PRIMARY KEY (id),
    CONSTRAINT ukt8o6pivur7nn124jehx7cygw5 UNIQUE (name)
);

ALTER TABLE categories ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME categories_id_seq START WITH 1 INCREMENT BY 1);

INSERT INTO categories (id, description, name, deleted) VALUES
(1, 'Desktop ve Laptop', 'Bilgisayar', false),
(2, 'Akıllı telefonlar', 'Telefon', false),
(3, 'Kablosuz ve Kablolu Kulaklıklar', 'Kulaklık', false),
(4, 'Mekanik ve membrane klavyeler', 'Klavye', false),
(5, 'Gaming ve ofis mouseları', 'Mouse', false);

-- ============================================================
-- PRODUCTS
-- ============================================================
CREATE TABLE products (
    id bigint NOT NULL,
    currency character varying(255) NOT NULL,
    description text,
    image_url character varying(255),
    name character varying(255) NOT NULL,
    price numeric(38,2) NOT NULL,
    category_id bigint NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    active boolean DEFAULT true NOT NULL,
    CONSTRAINT products_pkey PRIMARY KEY (id),
    CONSTRAINT fkog2rp4qthbtt2lfyhfo32lsw9 FOREIGN KEY (category_id) REFERENCES categories(id)
);

ALTER TABLE products ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME products_id_seq START WITH 1 INCREMENT BY 1);

INSERT INTO products (id, currency, description, image_url, name, price, category_id, deleted, active) VALUES
(1, 'TRY', 'M3 Pro, 18GB RAM, 512GB SSD', null, 'MacBook Pro 14', 59999.99, 1, false, true),
(2, 'TRY', 'Intel i7, 16GB RAM', null, 'Dell XPS 15', 54999.99, 1, false, true),
(3, 'TRY', 'Intel i7, 16GB RAM', null, 'Lenovo ThinkPad X1', 49999.99, 1, false, true),
(4, 'TRY', 'Intel i7, 16GB RAM', null, 'HP Spectre', 52999.99, 1, false, true),
(5, 'TRY', 'Ryzen 9, RTX 4070', null, 'ASUS ROG Zephyrus', 69999.99, 1, false, true),
(6, 'TRY', 'Intel i9, RTX 4080', null, 'MSI Stealth', 89999.99, 1, false, true),
(7, 'TRY', '256GB, Titanium', null, 'iPhone 15 Pro', 64999.99, 2, false, true),
(8, 'TRY', '256GB, Titanium Gray', null, 'Samsung S24 Ultra', 59999.99, 2, false, true),
(9, 'TRY', '512GB, Leica', null, 'Xiaomi 14', 34999.99, 2, false, true),
(10, 'TRY', '256GB, Snapdragon 8 Gen 3', null, 'OnePlus 12', 29999.99, 2, false, true),
(11, 'TRY', '128GB, Tensor G3', null, 'Google Pixel 8', 27999.99, 2, false, true),
(12, 'TRY', 'USB-C, ANC', null, 'AirPods Pro 2', 9999.99, 3, false, true),
(13, 'TRY', 'Kablosuz, ANC', null, 'Sony WH-1000XM5', 12999.99, 3, false, true),
(14, 'TRY', 'Kablosuz, ANC', null, 'JBL Tune 770NC', 3999.99, 3, false, true),
(15, 'TRY', 'Kablosuz, ANC', null, 'Samsung Galaxy Buds2', 4999.99, 3, false, true),
(16, 'TRY', 'Kablosuz, ANC', null, 'Bose QC45', 11999.99, 3, false, true),
(17, 'TRY', 'Bluetooth, numeric', null, 'Apple Magic Keyboard', 5999.99, 4, false, true),
(18, 'TRY', 'Bluetooth, backlight', null, 'Logitech MX Keys', 4499.99, 4, false, true),
(19, 'TRY', 'Mechanical, RGB', null, 'Razer BlackWidow V4', 7999.99, 4, false, true),
(20, 'TRY', 'Mechanical, RGB', null, 'Corsair K100', 6999.99, 4, false, true),
(21, 'TRY', 'Mechanical, adjustable', null, 'SteelSeries Apex Pro', 8999.99, 4, false, true),
(22, 'TRY', 'Bluetooth, ergonomic', null, 'Logitech MX Master 3S', 3999.99, 5, false, true),
(23, 'TRY', 'Gaming, 30000 DPI', null, 'Razer DeathAdder V3', 2999.99, 5, false, true),
(24, 'TRY', 'Bluetooth, Multi-Touch', null, 'Apple Magic Mouse', 4499.99, 5, false, true),
(25, 'TRY', 'Gaming, 18000 DPI', null, 'SteelSeries Rival 5', 2499.99, 5, false, true),
(26, 'TRY', 'Gaming, 12000 DPI', null, 'Corsair Harpoon', 1499.99, 5, false, true);

-- ============================================================
-- INVENTORY
-- ============================================================
CREATE TABLE inventory (
    id bigint NOT NULL,
    available_quantity integer NOT NULL,
    reserved_quantity integer NOT NULL,
    product_id bigint NOT NULL,
    version integer DEFAULT 0 NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (id),
    CONSTRAINT ukce3rbi3bfstbvvyne34c1dvyv UNIQUE (product_id),
    CONSTRAINT fkq2yge7ebtfuvwufr6lwfwqy9l FOREIGN KEY (product_id) REFERENCES products(id)
);

ALTER TABLE inventory ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME inventory_id_seq START WITH 1 INCREMENT BY 1);

INSERT INTO inventory (id, available_quantity, reserved_quantity, product_id, version) VALUES
(1, 10, 0, 1, 0),
(2, 10, 0, 17, 0);

-- ============================================================
-- USER_ADDRESSES
-- ============================================================
CREATE TABLE user_addresses (
    id bigint NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255) NOT NULL,
    country character varying(255) NOT NULL,
    district character varying(255) NOT NULL,
    street character varying(255) NOT NULL,
    zip_code character varying(255) NOT NULL,
    user_id bigint NOT NULL,
    is_default boolean DEFAULT false NOT NULL,
    deleted boolean DEFAULT false NOT NULL,
    CONSTRAINT user_addresses_pkey PRIMARY KEY (id),
    CONSTRAINT fkn2fisxyyu3l9wlch3ve2nocgp FOREIGN KEY (user_id) REFERENCES users(id)
);

ALTER TABLE user_addresses ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME user_addresses_id_seq START WITH 1 INCREMENT BY 1);

-- ============================================================
-- ORDERS
-- ============================================================
CREATE TABLE orders (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    order_number character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    total_price numeric(38,2) NOT NULL,
    user_id bigint NOT NULL,
    address_id bigint NOT NULL,
    CONSTRAINT orders_pkey PRIMARY KEY (id),
    CONSTRAINT uknthkiu7pgmnqnu86i2jyoe2v7 UNIQUE (order_number),
    CONSTRAINT fk32ql8ubntj5uh44ph9659tiih FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fkebxbj09m4a87s8na3lr86xnf4 FOREIGN KEY (address_id) REFERENCES user_addresses(id)
);

ALTER TABLE orders ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME orders_id_seq START WITH 1 INCREMENT BY 1);

-- ============================================================
-- ORDER_ITEMS
-- ============================================================
CREATE TABLE order_items (
    id bigint NOT NULL,
    price numeric(38,2) NOT NULL,
    product_name character varying(255) NOT NULL,
    quantity integer NOT NULL,
    order_id bigint NOT NULL,
    product_id bigint NOT NULL,
    CONSTRAINT order_items_pkey PRIMARY KEY (id),
    CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fkocimc7dtr037rh4ls4l95nlfi FOREIGN KEY (product_id) REFERENCES products(id)
);

ALTER TABLE order_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (SEQUENCE NAME order_items_id_seq START WITH 1 INCREMENT BY 1);
